# Generated by Django 2.2.12 on 2022-05-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fileid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileif', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='xinxi',
            name='imgcen',
        ),
    ]
