# Generated by Django 2.2.12 on 2022-05-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdapp', '0002_auto_20220507_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentnum',
        ),
    ]
