# Generated by Django 2.2.12 on 2022-05-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdapp', '0004_auto_20220507_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='num',
            name='num',
            field=models.IntegerField(),
        ),
    ]
