# Generated by Django 2.2.12 on 2022-05-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdapp', '0007_auto_20220509_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='xinxi',
            name='cover_pic',
            field=models.CharField(default='', max_length=250),
        ),
    ]
