# Generated by Django 2.2.12 on 2022-05-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdapp', '0008_xinxi_cover_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='num',
            name='file_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
